package service.dto;

public enum ServiceReturnCode {
	OK,USER_EXIST,PROVIDER_EXIST,WRONG_REQUEST,
	USER_NOT_FOUND,PROVIDER_NOT_FOUND,NO_SERVICES,
	SERVICE_NOT_FOUND,SCHEDULE_ALREDY_EXIST,SCHEDULE_NOT_FOUND,SERVICE_EXIST, RECORD_NOT_FOUND,TIME_NOT_EMPTY,PROVIDER_NOT_AVAIBALE
}
